name: Deploy Bookdown Notes

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev fontconfig libfreetype6-dev libharfbuzz-dev libfribidi-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "bookdown", "knitr"))'

      - name: Render Book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
